# Churn Modelling using ANN


In this project we'll be finding out if a customer is going to leave a bank using an ANN based on the datset that we have take from kaggle.

### Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder();
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

1.Importing Libraries:

The necessary libraries, ColumnTransformer from sklearn.compose and OneHotEncoder from sklearn.preprocessing, are imported.

2.Creating the ColumnTransformer:

The ColumnTransformer is initialized with the transformers parameter, which is a list of tuples.
In this case, the tuple consists of:
The string 'encoder', which serves as an identifier for the transformer.
An instance of the OneHotEncoder class, which will be used to perform one-hot encoding.
The list [1], which specifies the index of the column(s) to which the transformer should be applied. Here, it indicates that the one-hot encoding transformation should be applied to the column with index 1 (the second column).

The remainder parameter is set to 'passthrough', which means any remaining columns not explicitly transformed will be passed through without any changes.

3.Transforming the Data:

The fit_transform() method of the ColumnTransformer is called on the input data X. This method applies the transformations specified in the ColumnTransformer to the input data.

4.The resulting transformed data is stored in the variable X.
Note that the transformed data is converted to a NumPy array using np.array() in this code snippet. This step may be optional, depending on the specific requirements of your application.

In [ ]:
print(X) #encoded columns are moved to the first i columns

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #only transform() is applied on testset to prevent info leakage

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#units gives the number of neurons in the layer

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# activation is sigmoid for binary classification as it gives the probability of output belonging to that class
# for non-binary classification softmax is used

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# optimizer = adam performs stochastic gradient descent for ann(adjusts weights)
# loss = 'binary_crossentropy' for binary classification
# loss = 'categorical_crossentropy' for non-binary classification
# metrics - list of metrics for measuring nn's performance

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.7292 - accuracy: 0.5575
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6144 - accuracy: 0.7940
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5501 - accuracy: 0.7986
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4676 - accuracy: 0.8039
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4334 - accuracy: 0.8125
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4159 - accuracy: 0.8220
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3992 - accuracy: 0.8329
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3856 - accuracy: 0.8415
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3766 - accuracy: 0.8461
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3709 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation


Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,5000]]))>0.5)

1/1 [==============================] - 0s 23ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = y_pred>0.5
y_pred

63/63 [==============================] - 0s 1ms/step


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1513   82]
 [ 194  211]]
              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1595
           1       0.72      0.52      0.60       405

    accuracy                           0.86      2000
   macro avg       0.80      0.73      0.76      2000
weighted avg       0.85      0.86      0.85      2000

